apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fintechops
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "ChangeMe123!"
  JWT_SECRET: "fintechops-jwt-secret-2026-prod"
  COGNITO_USER_POOL_ID: "us-east-1_LpJTIudpS"
  COGNITO_CLIENT_ID: "6joqm59k47njd251dfrt25gvef"
  ALPHA_VANTAGE_KEY: "Q3UCENTUQQANX9UD"
