apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fintechops
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "<YOUR_DB_PASSWORD>"
  JWT_SECRET: "<YOUR_JWT_SECRET>"
  COGNITO_USER_POOL_ID: "<YOUR_COGNITO_POOL_ID>"
  COGNITO_CLIENT_ID: "<YOUR_COGNITO_CLIENT_ID>"
  ALPHA_VANTAGE_KEY: "<YOUR_ALPHA_VANTAGE_KEY>"
  GROWW_API_TOKEN: "<YOUR_GROWW_API_TOKEN>"
  GROWW_API_SECRET: "<YOUR_GROWW_API_SECRET>"
