apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fintechops
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "ChangeMe123!"
  JWT_SECRET: "fintechops-jwt-secret-2026-prod"
  COGNITO_USER_POOL_ID: "us-east-1_LpJTIudpS"
  COGNITO_CLIENT_ID: "6joqm59k47njd251dfrt25gvef"
  ALPHA_VANTAGE_KEY: "Q3UCENTUQQANX9UD"
  GROWW_API_TOKEN: "eyJraWQiOiJaTUtjVXciLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjI1NjAyNDI2OTAsImlhdCI6MTc3MTg0MjY5MCwibmJmIjoxNzcxODQyNjkwLCJzdWIiOiJ7XCJ0b2tlblJlZklkXCI6XCJlODg2MDQ1MC0zZGQ4LTQ4OGQtYjM5Ni1kZDhmMjJhMmUyNjVcIixcInZlbmRvckludGVncmF0aW9uS2V5XCI6XCJlMzFmZjIzYjA4NmI0MDZjODg3NGIyZjZkODQ5NTMxM1wiLFwidXNlckFjY291bnRJZFwiOlwiN2UwMDgxNmEtOThjNC00NjVlLWE5NzAtOTY3ZmExMDYzYjI0XCIsXCJkZXZpY2VJZFwiOlwiNTkyZWNhZjEtN2U4Zi01YzQ2LWFjMjMtNGUxYTA4NjUyZGZhXCIsXCJzZXNzaW9uSWRcIjpcImIxOTMyODMyLTQ5NmItNDgxNC1iMDdkLTVkYzI1ZWM1ZjM1OFwiLFwiYWRkaXRpb25hbERhdGFcIjpcIno1NC9NZzltdjE2WXdmb0gvS0EwYkw0RHFjWjJlK3VwRmtTRFNZNWZZc3hSTkczdTlLa2pWZDNoWjU1ZStNZERhWXBOVi9UOUxIRmtQejFFQisybTdRPT1cIixcInJvbGVcIjpcImF1dGgtdG90cFwiLFwic291cmNlSXBBZGRyZXNzXCI6XCIyYTA5OmJhYzU6M2FmNToxMWMzOjoxYzU6NDcsMTcyLjcwLjIxOS4yMDYsMzUuMjQxLjIzLjEyM1wiLFwidHdvRmFFeHBpcnlUc1wiOjI1NjAyNDI2OTA1NTl9IiwiaXNzIjoiYXBleC1hdXRoLXByb2QtYXBwIn0._3a3Qa36BC4HjE7jqAJqtUnnywFUgM7PPvD_hRN3x7lFJe8yVPBnf2BtxPCYOZyZ9QHCzC8ql9V51WyX3Jj3zg"
  GROWW_API_SECRET: "ZqNy-r@xogV%dWA@VF3-A6&E$W@w@FaY"
