apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: default
data:
  aws-region: "us-east-1"
  cognito-user-pool-id: "<your-user-pool-id>"
  cognito-client-id: "<your-client-id>"
  cognito-issuer: "https://cognito-idp.us-east-1.amazonaws.com/<your-user-pool-id>"
