apiVersion: v1
kind: Service
metadata:
  name: auth-frontend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: auth-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
