apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: default
type: Opaque
stringData:
  db-host: "<rds-endpoint>"
  db-port: "5432"
  db-name: "authdb"
  db-user: "<db-user>"
  db-password: "<db-password>"
