apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
  COGNITO_USER_POOL_ID: {{ .Values.cognito.userPoolId | quote }}
  COGNITO_CLIENT_ID: {{ .Values.cognito.clientId | quote }}
